version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8090:8090"
    volumes:
      - /backend/node_modules
      - ./backend:/backend
    environment:
      - MONGO_URI
    depends_on: 
      - mongo_db
    
  mongo_db:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    volumes:
      - mongo_data:/data/db
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - /frontend/node_modules
      - ./frontend:/frontend
    environment:
      - REACT_APP_BACKEND_URL
      - HTTPS=true
    depends_on: 
      - backend

volumes:
  mongo_data: